# Generated by Django 5.2.17 on 2026-09-25 12:36

import cabinet.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email (логин)"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
            managers=[
                ("objects", cabinet.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Имя / псевдоним"),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="ФИО / юр. лицо"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Заметки (видны только вам)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="аккаунт",
                    ),
                ),
            ],
            options={
                "verbose_name": "артист",
                "verbose_name_plural": "артисты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Например: Лицензионный договор",
                        max_length=300,
                        verbose_name="Название",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=100, verbose_name="Номер"),
                ),
                (
                    "signed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата подписания"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=cabinet.models.upload_contract,
                        verbose_name="Файл договора",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружен"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="cabinet.artist",
                        verbose_name="артист",
                    ),
                ),
            ],
            options={
                "verbose_name": "договор",
                "verbose_name_plural": "договоры",
                "ordering": ["-signed_date", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        default=cabinet.models.current_year, verbose_name="Год"
                    ),
                ),
                (
                    "quarter",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "I квартал"),
                            (2, "II квартал"),
                            (3, "III квартал"),
                            (4, "IV квартал"),
                        ],
                        verbose_name="Квартал",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=10, verbose_name="Валюта"
                    ),
                ),
                (
                    "detail_file",
                    models.FileField(
                        help_text="Файл от дистрибьютора. Из него строится таблица по трекам и площадкам; артист сможет скачать его целиком.",
                        upload_to=cabinet.models.upload_report,
                        verbose_name="Детализированный отчёт (Excel/CSV)",
                    ),
                ),
                (
                    "act_file",
                    models.FileField(
                        blank=True,
                        upload_to=cabinet.models.upload_act,
                        verbose_name="Акт для подписания",
                    ),
                ),
                (
                    "signed_act_file",
                    models.FileField(
                        blank=True,
                        help_text="Необязательно: скан акта, подписанного артистом.",
                        upload_to=cabinet.models.upload_signed_act,
                        verbose_name="Подписанный акт",
                    ),
                ),
                (
                    "act_status",
                    models.CharField(
                        choices=[
                            ("none", "Акт не загружен"),
                            ("to_sign", "Ожидает подписания"),
                            ("signed", "Подписан"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Статус акта",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Показывать артисту"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий для артиста"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=16,
                        verbose_name="Итого",
                    ),
                ),
                (
                    "total_quantity",
                    models.BigIntegerField(
                        default=0, editable=False, verbose_name="Всего прослушиваний"
                    ),
                ),
                (
                    "lines_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Строк в отчёте"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружен"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="cabinet.artist",
                        verbose_name="артист",
                    ),
                ),
            ],
            options={
                "verbose_name": "квартальный отчёт",
                "verbose_name_plural": "квартальные отчёты",
                "ordering": ["-year", "-quarter"],
            },
        ),
        migrations.CreateModel(
            name="RoyaltyLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track", models.CharField(max_length=500, verbose_name="Трек")),
                (
                    "isrc",
                    models.CharField(blank=True, max_length=20, verbose_name="ISRC"),
                ),
                ("platform", models.CharField(max_length=200, verbose_name="Площадка")),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="Страна"),
                ),
                (
                    "quantity",
                    models.BigIntegerField(default=0, verbose_name="Прослушивания"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=6, default=0, max_digits=18, verbose_name="Сумма"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="cabinet.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "строка отчёта",
                "verbose_name_plural": "строки отчёта",
            },
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("artist", "year", "quarter"), name="uniq_report_per_quarter"
            ),
        ),
        migrations.AddIndex(
            model_name="royaltyline",
            index=models.Index(
                fields=["report", "track"], name="cabinet_roy_report__a7e1dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royaltyline",
            index=models.Index(
                fields=["report", "platform"], name="cabinet_roy_report__398421_idx"
            ),
        ),
    ]
