# Generated by Django 5.2.17 on 2026-10-03 14:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Например: ИП Сайкин Михаил Викторович",
                        max_length=300,
                        verbose_name="Название (как в акте)",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=400, verbose_name="Адрес"),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=20, verbose_name="ИНН"),
                ),
                (
                    "ogrn",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ОГРН / ОГРНИП"
                    ),
                ),
                (
                    "signer",
                    models.CharField(
                        blank=True,
                        help_text="Например: Сайкин М.В.",
                        max_length=100,
                        verbose_name="Подпись (Фамилия И.О.)",
                    ),
                ),
                (
                    "payout_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5000"),
                        help_text="Меньшие суммы копятся до этого порога, но выплачиваются не позднее конца года.",
                        max_digits=12,
                        verbose_name="Минимальная сумма выплаты, ₽",
                    ),
                ),
            ],
            options={
                "verbose_name": "реквизиты лейбла",
                "verbose_name_plural": "реквизиты лейбла",
            },
        ),
        migrations.AddField(
            model_name="artist",
            name="address",
            field=models.CharField(
                blank=True, max_length=400, verbose_name="Адрес (для акта)"
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="inn",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="ИНН (для акта)"
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="royalty_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50"),
                help_text="Какой процент дохода лейбла получает артист по договору. В кабинете артист видит только свою долю.",
                max_digits=5,
                verbose_name="Доля артиста, %",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="act_date",
            field=models.DateField(
                blank=True,
                help_text="Если пусто — дата загрузки отчёта.",
                null=True,
                verbose_name="Дата акта",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Заполните после выплаты — сумма учтётся в следующих актах.",
                max_digits=14,
                verbose_name="Выплачено артисту по этому акту, ₽",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="royalty_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Если пусто — берётся доля из карточки артиста.",
                max_digits=5,
                null=True,
                verbose_name="Доля артиста, %",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="total_gross",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=16,
                verbose_name="Доход лейбла",
            ),
        ),
        migrations.AddField(
            model_name="royaltyline",
            name="gross",
            field=models.DecimalField(
                decimal_places=6, default=0, max_digits=18, verbose_name="Доход лейбла"
            ),
        ),
        migrations.AddField(
            model_name="royaltyline",
            name="rights_type",
            field=models.CharField(blank=True, max_length=100, verbose_name="Тип прав"),
        ),
        migrations.AlterField(
            model_name="report",
            name="act_status",
            field=models.CharField(
                choices=[
                    ("none", "Акт не загружен"),
                    ("to_sign", "Ожидает подписания"),
                    ("signed", "Подписан"),
                ],
                default="to_sign",
                max_length=10,
                verbose_name="Статус акта",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=16,
                verbose_name="Итого артисту",
            ),
        ),
        migrations.AlterField(
            model_name="royaltyline",
            name="amount",
            field=models.DecimalField(
                decimal_places=6, default=0, max_digits=18, verbose_name="Доля артиста"
            ),
        ),
    ]
