# Generated by Django 5.2.17 on 2026-10-08 17:37

import cabinet.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0002_royalty_share_acts"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Расчётный счёт"
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="bank_bik",
            field=models.CharField(blank=True, max_length=9, verbose_name="БИК"),
        ),
        migrations.AddField(
            model_name="artist",
            name="bank_corr_account",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Корр. счёт"
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="bank_name",
            field=models.CharField(blank=True, max_length=300, verbose_name="Банк"),
        ),
        migrations.AddField(
            model_name="artist",
            name="bank_recipient",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Получатель (ФИО полностью)"
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="bank_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Реквизиты обновлены"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="signed_uploaded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Подписанный акт загружен"
            ),
        ),
        migrations.AddField(
            model_name="royaltyline",
            name="usage_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Вид использования"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="act_status",
            field=models.CharField(
                choices=[
                    ("none", "Акт не загружен"),
                    ("to_sign", "Ожидает подписания"),
                    ("review", "На проверке"),
                    ("signed", "Подписан"),
                ],
                default="to_sign",
                max_length=10,
                verbose_name="Статус акта",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="signed_act_file",
            field=models.FileField(
                blank=True,
                help_text="Скан или фото акта, подписанного артистом. Артист может загрузить его сам из кабинета.",
                upload_to=cabinet.models.upload_signed_act,
                verbose_name="Подписанный акт",
            ),
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                (
                    "artists_line",
                    models.CharField(
                        blank=True,
                        help_text="Например: Эсчевский feat. Кто-то. Если пусто — имя артиста.",
                        max_length=300,
                        verbose_name="Исполнители (как на площадках)",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("single", "Сингл"),
                            ("ep", "EP"),
                            ("album", "Альбом"),
                        ],
                        default="single",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата релиза"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "Готовится"),
                            ("moderation", "На модерации"),
                            ("scheduled", "Отгружен, ждёт даты"),
                            ("released", "Вышел"),
                            ("taken_down", "Снят с площадок"),
                        ],
                        default="preparing",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "upc",
                    models.CharField(blank=True, max_length=20, verbose_name="UPC"),
                ),
                (
                    "isrc",
                    models.CharField(
                        blank=True,
                        help_text="Можно несколько через запятую",
                        max_length=100,
                        verbose_name="ISRC",
                    ),
                ),
                (
                    "smart_link",
                    models.URLField(
                        blank=True,
                        help_text="Например: https://band.link/…",
                        verbose_name="Смарт-ссылка",
                    ),
                ),
                (
                    "presave_date",
                    models.DateField(blank=True, null=True, verbose_name="Пресейв с"),
                ),
                (
                    "cover",
                    models.FileField(
                        blank=True,
                        upload_to=cabinet.models.upload_cover,
                        verbose_name="Обложка (jpg/png)",
                    ),
                ),
                (
                    "cover_url",
                    models.URLField(
                        blank=True,
                        help_text="Вставьте ссылку на картинку — сервер сам скачает её в «Обложку».",
                        verbose_name="…или ссылка на обложку",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Например: «Питчинг в Яндекс Музыку отправлен»",
                        max_length=300,
                        verbose_name="Заметка для артиста",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Показывать артисту"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлен"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="cabinet.artist",
                        verbose_name="артист",
                    ),
                ),
            ],
            options={
                "verbose_name": "релиз",
                "verbose_name_plural": "релизы",
                "ordering": ["-release_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaylistPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track", models.CharField(max_length=500, verbose_name="Трек")),
                ("platform", models.CharField(max_length=200, verbose_name="Площадка")),
                ("playlist", models.CharField(max_length=300, verbose_name="Плейлист")),
                (
                    "peak_position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Пиковая позиция"
                    ),
                ),
                (
                    "days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Дней в плейлисте"
                    ),
                ),
                (
                    "first_date",
                    models.DateField(blank=True, null=True, verbose_name="Первая дата"),
                ),
                (
                    "last_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Последняя дата"
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_placements",
                        to="cabinet.artist",
                    ),
                ),
            ],
            options={
                "verbose_name": "попадание в плейлист",
                "verbose_name_plural": "попадания в плейлисты",
                "ordering": ["-last_date", "peak_position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artist", "track", "platform", "playlist"),
                        name="uniq_playlist_placement",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StreamStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="С")),
                ("period_end", models.DateField(verbose_name="По")),
                ("track", models.CharField(max_length=500, verbose_name="Трек")),
                (
                    "platform",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Площадка"
                    ),
                ),
                (
                    "streams",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Прослушивания"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Источник"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now=True, verbose_name="Загружено"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_stats",
                        to="cabinet.artist",
                    ),
                ),
            ],
            options={
                "verbose_name": "прослушивания за период",
                "verbose_name_plural": "свежая статистика прослушиваний",
                "ordering": ["-period_end", "-streams"],
                "indexes": [
                    models.Index(
                        fields=["artist", "period_end"],
                        name="cabinet_str_artist__1f7a03_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "artist",
                            "period_start",
                            "period_end",
                            "track",
                            "platform",
                        ),
                        name="uniq_stream_stat",
                    )
                ],
            },
        ),
    ]
